### ISSUE TITLE
RaveCC

### ISSUE THREAD

**Issue by Legogris** [nsexer/blockchainweek.fr#14]
If you're submitting an event, please read the instructions below and fill in
the content. Otherwise just remove all the content of this issue and explain
in detail the problem you're experiencing.

---
####################
####################
# This file is a template to create new events.
# _Don't_ remove any text before the colons at the beginning of each line,
# only edit what is after the colon. Example:
# Don't remove the word nor colon on 'description:'
#
# Every line starting with a hash symbol (#) is a comment. It will be ignored
# and can be safely removed, including these instructions.
###############

###########
###########
# The title of the page, displayed by the browser on the title of the window.
# Ideally this is the same as the name of the event.
title: RaveCC 2019

# Description for this event. This will be rendered as a <meta> tag in the HTML,
# and displayed on the /events page. Keep it short.
# Linebreaks are ignored, but they _must_ start with two spaces.
description: Come lose yourself in the ether with fellow crypto freaks during the Community Blockchain Week in Paris. 

#####################
#####################
# The name of the event you're creating.
# Ideally this is the same as the title.
name: RaveCC 2019

# There _needs_ to be one hyphen before each paragraph.
# Linebreaks are ignored, but they _must_ start with two spaces.
# Indentation is crucial:
# Two spaces before the hyphen, four spaces before the text. _No_ tabs allowed.
# Add or remove paragraphs as needed, but remember the hyphen before each entry.
synopsis:

  -

Come lose yourself in the ether with fellow crypto freaks during the Community Blockchain Week in Paris.

  -

Location accessible from central Paris and the EthCC venue.

Drinks will be payable in cash, ETH and DAI.

Timetable TBA

Tech house / minimal / trance

Due to a long bear winter, we have to ask for a contribution for attending. If you are intending to attend, please register ASAP and spread the word. Entry includes one drink ticket. If we cover the costs the bar will be an open one - this is for community, not for profit. The party will be going until the morning hours.

**PLUR / One Tribe**
☮️ 💓 🕉️ 🙇‍♀️

Register by the Evenbrite link, or by sending an e-mail to ravecc@protonmail.com with your name and a reference to a transaction of 10 EUR worth to one of the following addresses:

* **ETH/DAI**: 0x85C980Ef7a207df71cbe4EFa1974dF7076A8a76B 
* **BTC**: 18EHWWWNoqpN9DtKAVmX9dTJkuir6qWzvC / 33B8jD3eWnnjasb6uPSWZjj9Lgsp8gXX7L / bc1qs8ull4ghw2hasu3ygr509ng6mcaupky4kwruyn

  -

This event is non-sponsored as of now - if your team wants to help make this as awesome as it can be, contact at ravecc@protonmail.com

# The date should be in the format year-month-day (ISO 8601).
# Example: 2018-02-28
date: 2019-03-07
# The date when the event ends. Can be left empty or set to the same day the
# event starts.
# endDate: 2019-03-08

# Set the time in 24 hours format, surrounded by quotes.
# _Only_ the starting time!
# Example: '18:00'
time: '22:00'
# Time when the event ends. Can be left empty.
endTime: '05:00'

# The URL where to akquire the tickets. Can be left empty.
tickets: https://www.eventbrite.com/e/ravecc-2019-tickets-57515499407

# If the entrance is free, set zero (0) as the price, or leave it empty.
# _Don't_ write the currency symbol (Euro symbol will be used).
price: 10

# The name of the venue where the event will be held. Can be left empty.
venue: SECRET LOCATION

# The address to link to a Google map. Please test the address on Google Maps.
# Example: Skalitzer Strasse 85-86, 10997 Berlin, Germany
# address: Skalitzer Strasse 85-86, 10997 Berlin, Germany

# The category of the event. Valid options:
# - conference
# - event
# - hackathon
# - panel
# - workshop
# - party
# Use _only_ one, and don't capitalize.
category: event

#################
#################
# There _needs_ to be one hyphen before each entry.
# Linebreaks are ignored, but they _must_ start with two spaces.
# Indentation is crucial:
# Two spaces before the hyphen, four spaces before the text. _No_ tabs allowed.
# Add or remove speakers as needed, but remember the hyphen before each entry.
speakers:

### DON'T MAKE CHANGES BELOW THIS LINE! ###
---

<Event-Content/>

**Comment by Legogris** [comment]
https://i.imgur.com/V18HG40.png

**Comment by Legogris** [comment]
@nsexer realized that setting the enddate on the next day makes in appear on Friday as well in the calendar - could you remove the endDate and add this to the description?
`The party will be going until the morning hours.`

Issue updated accordingly.

**Comment by nsexer** [comment]
Sure will do
