### ISSUE TITLE
Building Decentralized Backends Workshop

### ISSUE THREAD

**Issue by lekanova** [nsexer/blockchainweek.fr#15]
If you're submitting an event, please read the instructions below and fill in
the content. Otherwise just remove all the content of this issue and explain
in detail the problem you're experiencing.

---
####################
####################
# This file is a template to create new events.
# _Don't_ remove any text before the colons at the beginning of each line,
# only edit what is after the colon. Example:
# Don't remove the word nor colon on 'description:'
#
# Every line starting with a hash symbol (#) is a comment. It will be ignored
# and can be safely removed, including these instructions.
###############

###########
###########
# The title of the page, displayed by the browser on the title of the window.
# Ideally this is the same as the name of the event.
title: Building Scalable Decentralized Backends. Workshop.

# Description for this event. This will be rendered as a <meta> tag in the HTML,
# and displayed on the /events page. Keep it short.
# Linebreaks are ignored, but they _must_ start with two spaces.
description: Developing DApps that are something more than just a set of smart contracts today requires a lot of effort and skill. Fluence Network creates a decentralized environment that makes DApps backend development frictionless and straightforward.

#####################
#####################
# The name of the event you're creating.
# Ideally this is the same as the title.
name: Building Scalable Decentralized Backends. Workshop.

# There _needs_ to be one hyphen before each paragraph.
# Linebreaks are ignored, but they _must_ start with two spaces.
# Indentation is crucial:
# Two spaces before the hyphen, four spaces before the text. _No_ tabs allowed.
# Add or remove paragraphs as needed, but remember the hyphen before each entry.
synopsis:
  -
    At the workshop, you will have a hands-on experience with Fluence Devnet — a decentralized network where you can deploy your own arbitrary code or set up a database.
  -
    The plan is simple: 
    - Short intro on how Fluence approaches decentralization and what makes it fit for app development.
    - Hacking with the Devnet and a set of developer tools we've prepared
  -
    The venue is right next to EthCC conference.   
    Bring Your Own Laptop!
    For any questions, please, reach out to the team in Discord: https://discord.gg/mt86peA

# The date should be in the format year-month-day (ISO 8601).
# Example: 2018-02-28
date: 2019-03-06
# The date when the event ends. Can be left empty or set to the same day the
# event starts.
endDate: 2019-03-06

# Set the time in 24 hours format, surrounded by quotes.
# _Only_ the starting time!
# Example: '18:00'
time: '18:30'
# Time when the event ends. Can be left empty.
endTime: '21:00'

# The URL where to akquire the tickets. Can be left empty.
tickets: https://www.eventbrite.com/e/building-scalable-decentralized-backends-workshop-tickets-57724001041

# If the entrance is free, set zero (0) as the price, or leave it empty.
# _Don't_ write the currency symbol (Euro symbol will be used).
price: 0

# The name of the venue where the event will be held. Can be left empty.
venue: Coinhouse

# The address to link to a Google map. Please test the address on Google Maps.
# Example: Skalitzer Strasse 85-86, 10997 Berlin, Germany
address: Rue du Caire 35, 75002 Paris, France

# The category of the event. Valid options:
# - conference
# - event
# - hackathon
# - panel
# - workshop
# - party
# Use _only_ one, and don't capitalize.
category: workshop

#################
#################
# There _needs_ to be one hyphen before each entry.
# Linebreaks are ignored, but they _must_ start with two spaces.
# Indentation is crucial:
# Two spaces before the hyphen, four spaces before the text. _No_ tabs allowed.
# Add or remove speakers as needed, but remember the hyphen before each entry.
speakers:
  -
    # Required.
    name: Dmitry Kurinskiy

    # Can be left empty.
    title: CTO & Co-Founder

    # Can be left empty.
    company: Fluence Labs

    # The full URL, including http(s)://. Can be left empty.
    companyURL: https://fluence.network

    # Just the twitter handle, without Twitter's URL, nor the '@' symbol.
    # Can be left empty.
    twitter: Fluence_One

    # The full URL, including http(s)://. Can be left empty.
    website: https://github.com/alari

    # The bio is a single line.
    # Linebreaks are ignored, but they _must_ start with two spaces.
    bio: Dmitry is a software engineer and technical leader, with solid expertise in complex engineering projects since 2004. Keen functional programming advocate.

### DON'T MAKE CHANGES BELOW THIS LINE! ###
---

<Event-Content/>

**Comment by nsexer** [comment]
Its live! https://blockchainweek.fr/events/fluence/ 
Feel free to share (and mention @ComBlockWeek :)
