### ISSUE TITLE
'Web3 Stack, what's next for developers?' @ConsenSys

### ISSUE THREAD

**Issue by lekanova** [nsexer/blockchainweek.fr#16]
If you're submitting an event, please read the instructions below and fill in
the content. Otherwise just remove all the content of this issue and explain
in detail the problem you're experiencing.

---
####################
####################
# This file is a template to create new events.
# _Don't_ remove any text before the colons at the beginning of each line,
# only edit what is after the colon. Example:
# Don't remove the word nor colon on 'description:'
#
# Every line starting with a hash symbol (#) is a comment. It will be ignored
# and can be safely removed, including these instructions.
###############

###########
###########
# The title of the page, displayed by the browser on the title of the window.
# Ideally this is the same as the name of the event.
title: Web3 stack, what’s next for developers? @ConsenSys

# Description for this event. This will be rendered as a <meta> tag in the HTML,
# and displayed on the /events page. Keep it short.
# Linebreaks are ignored, but they _must_ start with two spaces.
description: Tech presentations + demos from Fluence, IPFS & NuCypher.

#####################
#####################
# The name of the event you're creating.
# Ideally this is the same as the title.
name: Web3 stack, what’s next for developers? @ConsenSys

# There _needs_ to be one hyphen before each paragraph.
# Linebreaks are ignored, but they _must_ start with two spaces.
# Indentation is crucial:
# Two spaces before the hyphen, four spaces before the text. _No_ tabs allowed.
# Add or remove paragraphs as needed, but remember the hyphen before each entry.
synopsis:
  -
    Let’s get together to challenge the current limits of a decentralized world with a diversity of BUIDLing approaches. Join us for tech breakdowns on the latest developments across the decentralized stack solutions.
  -
    Each project will have a technical overview presentation. You'll learn about the developments in decentralized file storage, decentralized data processing, privacy-preserving techniques for decentralized data sharing and storage, and other base-layers implementations.

# The date should be in the format year-month-day (ISO 8601).
# Example: 2018-02-28
date: 2019-03-08
# The date when the event ends. Can be left empty or set to the same day the
# event starts.
endDate: 2019-03-08

# Set the time in 24 hours format, surrounded by quotes.
# _Only_ the starting time!
# Example: '18:00'
time: '12:30'
# Time when the event ends. Can be left empty.
endTime: '14:30'

# The URL where to akquire the tickets. Can be left empty.
tickets: https://www.eventbrite.com/e/web3-stack-whats-next-for-developers-consensys-tickets-57699644189

# If the entrance is free, set zero (0) as the price, or leave it empty.
# _Don't_ write the currency symbol (Euro symbol will be used).
price: 0

# The name of the venue where the event will be held. Can be left empty.
venue: ConsenSys France

# The address to link to a Google map. Please test the address on Google Maps.
# Example: Skalitzer Strasse 85-86, 10997 Berlin, Germany
address: Rue Vauvilliers 10, 75001 Paris, France

# The category of the event. Valid options:
# - conference
# - event
# - hackathon
# - panel
# - workshop
# - party
# Use _only_ one, and don't capitalize.
category: event

#################
#################
# There _needs_ to be one hyphen before each entry.
# Linebreaks are ignored, but they _must_ start with two spaces.
# Indentation is crucial:
# Two spaces before the hyphen, four spaces before the text. _No_ tabs allowed.
# Add or remove speakers as needed, but remember the hyphen before each entry.
speakers:
  -
    # Required.
    name: Dmitry Kurinskiy

    # Can be left empty.
    title: CTO & Co-founder

    # Can be left empty.
    company: Fluence Labs

    # The full URL, including http(s)://. Can be left empty.
    companyURL: http://fluence.network/

    # Just the twitter handle, without Twitter's URL, nor the '@' symbol.
    # Can be left empty.
    twitter: https://twitter.com/name_alari

    # The full URL, including http(s)://. Can be left empty.
    website: https://github.com/alari

    # The bio is a single line.
    # Linebreaks are ignored, but they _must_ start with two spaces.
    bio: Software engineer and technical leader, with solid expertise in complex engineering projects since 2004. Keen functional programming advocate.
  -
    name: Portia Burton
    title: Community Engineer
    company: Protocol Labs
    companyURL: https://protocol.ai/
    twitter: pkafei
    website: https://github.com/pkafei 
    bio: Portia is an experienced blockchain developer creating the foundation for a decentralized world.
  -
    name: MacLane Wilkison
    title: CEO & Co-founder 
    company: NuCypher
    companyURL: https://www.nucypher.com
    twitter: MacLaneWilkison
    website: https://github.com/mswilkison
    bio: MacLane is a software engineer and former investment banker at Morgan Stanley. He is a Certified Information Systems Security Professional (CISSP) and Chartered Financial Analyst (CFA).

### DON'T MAKE CHANGES BELOW THIS LINE! ###
---

<Event-Content/>

**Comment by nsexer** [comment]
Done! https://blockchainweek.fr/events/web3stack/
