### ISSUE TITLE
Paris P2P #7

### ISSUE THREAD

**Issue by moul** [nsexer/blockchainweek.fr#20]
title: Paris P2P #7

description: Monthly Peer-to-Beer of the Parisian community interested in all things P2P

name: Paris P2P #7

synopsis:
  -
    Each month, the Parisian community interested in all things P2P meets and share about cryptography, privacy, commons, shared governance, DAPPs, DAOs, Web3 and the blockchains.

date: 2020-03-04
endDate: 2020-03-04

time: '19:00'
endTime: '23:30'

tickets: https://p2p.paris/en/event/monthly-7/

price: 0

venue: Ground Control, Paris

address: 81 Rue du Charolais, 75012 Paris

category: event

speakers:
  -
    name: Caleb James Delisle
    title: cjdns
    company: Lead developer of cjdns
    companyURL: https://github.com/cjdelisle/cjdns
    twitter: cjdelisle
    website: https://p2p.paris/en/speakers/caleb-james-delisle/
    bio: Caleb James DeLisle, the lead developer of cjdns, an encrypted IPv6 networking protocol and server software that uses public key cryptography for address allocation and a distributed hash table for routing.
  -
    name: Pierre Boc
    title: Ops of Berty
    company: Berty Technologies
    companyURL: https://berty.tech/
    twitter: pierreboc
    website: https://p2p.paris/en/speakers/pierre-boc/
    bio: Pierre manages operations at Berty Technologies in order to create new secure communication tools to protect the privacy and protect against censorship.

---

<Event-Content/>

**Comment by nsexer** [comment]
It's live: https://blockchainweek.fr/events/parisP2P/
Make some noise!

**Comment by nsexer** [comment]
Live: https://twitter.com/blockweekfr/status/1230778065573351425?s=21

--
Nathan Sexer

**Comment by pierreboc** [comment]
Hello, first of all thank you for relaying the information :) 
Just a little message to point out a typo: my name is Pierre Boc but on the site, it says "ops of Berty" (https://blockchainweek.fr/events/parisP2P/)
Thank you ;)
