### ISSUE TITLE
Computational Law and Blockchain Festival

### ISSUE THREAD

**Issue by Xalava** [nsexer/blockchainweek.fr#3]
---
###########
###########
# The title of the page, displayed by the browser on the title of the window.
# Ideally this is the same as the name of the event.
title: Computational Law and Blockchain Festival Paris
# Description for this event. 
description: Conference, workshops and hackathon about law and blockchain technologies

#####################
#####################
synopsis:
  -
    Conference, policy and tech workshops, and hackathon
  -
    The second edition of the Computational Law and Blockchain Festival Paris aims to bring meaningful 
    conversations through a hands-on approach 

# The date should be in the format year-month-day (ISO 8601).
# Example: 2018-02-28
date: 2019-03-01
# The date when the event ends. Can be left empty or set to the same day the
# event starts.
endDate: 2019-03-03

# Set the time in 24 hours format, surrounded by quotes.
# _Only_ the starting time!
# Example: '18:00'
time: '14:00'
# Time when the event ends. Can be left empty.
endTime: '16:00'

# The URL where to aquire the tickets. Can be left empty.
tickets: http://bit.ly/CLBFest2019

# If the entrance is free, set zero (0) as the price, or leave it empty.
# _Don't_ write the currency symbol (Euro symbol will be used).
price: 0

# The name of the venue where the event will be held. Can be left empty.
venue: The Square Paris

# The address to link to a Google map. Please test the address on Google Maps.
address: 3 passage Saint Pierre Amelot, 75010 Paris, France

# The category of the event. 
category: hackathon

#################
#################

### DON'T MAKE CHANGES BELOW THIS LINE! ###
---

<Event-Content/>

**Comment by nsexer** [comment]
Added
